server:
  port: 8000
  servlet:
    context-path: /pay

spring:
  application:
    name: micr-pay
  thymeleaf:
    cache: false

  redis:
    port: 6379
    host: 1.14.12.49

dubbo:
  registry:
    address: zookeeper://1.14.12.49:2181
  scan:
    base-packages: com.ylb.work.pay
  consumer:
    timeout: 60000
    check: false
    retries: 0

