package com.ylb.work.dataservice.mapper;

import com.node.api.pojo.IncomeRecord;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface IncomeRecordMapper {


    List<IncomeRecord> selectExpiredIncome(@Param("expired") Date expired);

    List<IncomeRecord> selectIncomeRecordByUid(@Param("uid") Integer uid,
                                               @Param("offset") int offset,
                                               @Param("rows") Integer pageSize);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int insert(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int insertSelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    IncomeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int updateByPrimaryKeySelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int updateByPrimaryKey(IncomeRecord record);



}