package com.ylb.work.dataservice.mapper;

import com.node.api.model.MultiProduct;
import com.node.api.pojo.ProductInfo;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public interface ProductInfoMapper {

    // 更新产品状态
    int updateProductStatus(@Param("id") Integer id, @Param("status") int productStatus);

    // 查询已满标产品
    List<ProductInfo> selectFullTimeProducts(@Param("beginTime") Date beginTime, @Param("endTime") Date endTime);

    // 更新产品状态
    int updateSelled(@Param("id") Integer productId);

    // 更新账户剩余购买金额
    int updateLeftProductMoney(@Param("id") Integer productId, @Param("money") BigDecimal money);

    // 根据产品 id 查询产品详情
    ProductInfo selectProductInfoById(@Param("productId") Integer productId);

    // 根据产品类型查询产品总数
    Integer selectCountByType(@Param("pType") Integer productType);

    // 根据产品类型分页查询产品
    List<ProductInfo> selectByTypeLimit(@Param("pType") Integer productType,
                                        @Param("offset") Integer offset,
                                        @Param("rows") Integer rows);


    // 查询利率平均值
    BigDecimal selectAvgRate();





    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int insert(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int insertSelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    ProductInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int updateByPrimaryKeySelective(ProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_info
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int updateByPrimaryKey(ProductInfo record);



}