package com.ylb.work.dataservice.mapper;

import com.node.api.pojo.RechargeRecord;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RechargeRecordMapper {


    int updateStatus(@Param("id") Integer id, @Param("status") int rechargeStatusSuccess);

    RechargeRecord selectByRechargeNo(@Param("rechargeNo") String orderId);

    // 根据用户 id 查询投资记录，分页
    List<RechargeRecord> selectRechargeRecordByUid(@Param("uid") Integer uid,
                                                   @Param("offset") Integer offset,
                                                   @Param("rows") Integer rows);






    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int insert(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int insertSelective(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    RechargeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int updateByPrimaryKeySelective(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_recharge_record
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    int updateByPrimaryKey(RechargeRecord record);



}