package com.node.api.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BidInfo implements Serializable {
    private static final long serialVersionUID = 7174387114700579926L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bid_info.id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bid_info.loan_id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer loanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bid_info.uid
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bid_info.bid_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private BigDecimal bidMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bid_info.bid_time
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Date bidTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_bid_info.bid_status
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer bidStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bid_info.id
     *
     * @return the value of b_bid_info.id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bid_info.id
     *
     * @param id the value for b_bid_info.id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bid_info.loan_id
     *
     * @return the value of b_bid_info.loan_id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bid_info.loan_id
     *
     * @param loanId the value for b_bid_info.loan_id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setLoanId(Integer loanId) {
        this.loanId = loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bid_info.uid
     *
     * @return the value of b_bid_info.uid
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bid_info.uid
     *
     * @param uid the value for b_bid_info.uid
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bid_info.bid_money
     *
     * @return the value of b_bid_info.bid_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public BigDecimal getBidMoney() {
        return bidMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bid_info.bid_money
     *
     * @param bidMoney the value for b_bid_info.bid_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setBidMoney(BigDecimal bidMoney) {
        this.bidMoney = bidMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bid_info.bid_time
     *
     * @return the value of b_bid_info.bid_time
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Date getBidTime() {
        return bidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bid_info.bid_time
     *
     * @param bidTime the value for b_bid_info.bid_time
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setBidTime(Date bidTime) {
        this.bidTime = bidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_bid_info.bid_status
     *
     * @return the value of b_bid_info.bid_status
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getBidStatus() {
        return bidStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_bid_info.bid_status
     *
     * @param bidStatus the value for b_bid_info.bid_status
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setBidStatus(Integer bidStatus) {
        this.bidStatus = bidStatus;
    }
}