package com.node.api.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class IncomeRecord implements Serializable {
    private static final long serialVersionUID = 3045007177890481859L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.uid
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.loan_id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer loanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.bid_id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer bidId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.bid_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private BigDecimal bidMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.income_date
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Date incomeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.income_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private BigDecimal incomeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_income_record.income_status
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer incomeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.id
     *
     * @return the value of b_income_record.id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.id
     *
     * @param id the value for b_income_record.id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.uid
     *
     * @return the value of b_income_record.uid
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.uid
     *
     * @param uid the value for b_income_record.uid
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.loan_id
     *
     * @return the value of b_income_record.loan_id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.loan_id
     *
     * @param loanId the value for b_income_record.loan_id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setLoanId(Integer loanId) {
        this.loanId = loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.bid_id
     *
     * @return the value of b_income_record.bid_id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getBidId() {
        return bidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.bid_id
     *
     * @param bidId the value for b_income_record.bid_id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setBidId(Integer bidId) {
        this.bidId = bidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.bid_money
     *
     * @return the value of b_income_record.bid_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public BigDecimal getBidMoney() {
        return bidMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.bid_money
     *
     * @param bidMoney the value for b_income_record.bid_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setBidMoney(BigDecimal bidMoney) {
        this.bidMoney = bidMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.income_date
     *
     * @return the value of b_income_record.income_date
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Date getIncomeDate() {
        return incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.income_date
     *
     * @param incomeDate the value for b_income_record.income_date
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setIncomeDate(Date incomeDate) {
        this.incomeDate = incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.income_money
     *
     * @return the value of b_income_record.income_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public BigDecimal getIncomeMoney() {
        return incomeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.income_money
     *
     * @param incomeMoney the value for b_income_record.income_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setIncomeMoney(BigDecimal incomeMoney) {
        this.incomeMoney = incomeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_income_record.income_status
     *
     * @return the value of b_income_record.income_status
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getIncomeStatus() {
        return incomeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_income_record.income_status
     *
     * @param incomeStatus the value for b_income_record.income_status
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setIncomeStatus(Integer incomeStatus) {
        this.incomeStatus = incomeStatus;
    }
}