package com.node.api.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ProductInfo implements Serializable {
    private static final long serialVersionUID = 7984066343617003337L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_name
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.rate
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private BigDecimal rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.cycle
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer cycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.release_time
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Date releaseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_type
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_no
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private BigDecimal productMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.left_product_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private BigDecimal leftProductMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.bid_min_limit
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private BigDecimal bidMinLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.bid_max_limit
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private BigDecimal bidMaxLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_status
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Integer productStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_full_time
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private Date productFullTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_info.product_desc
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    private String productDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.id
     *
     * @return the value of b_product_info.id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.id
     *
     * @param id the value for b_product_info.id
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_name
     *
     * @return the value of b_product_info.product_name
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_name
     *
     * @param productName the value for b_product_info.product_name
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.rate
     *
     * @return the value of b_product_info.rate
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.rate
     *
     * @param rate the value for b_product_info.rate
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.cycle
     *
     * @return the value of b_product_info.cycle
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.cycle
     *
     * @param cycle the value for b_product_info.cycle
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.release_time
     *
     * @return the value of b_product_info.release_time
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.release_time
     *
     * @param releaseTime the value for b_product_info.release_time
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_type
     *
     * @return the value of b_product_info.product_type
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_type
     *
     * @param productType the value for b_product_info.product_type
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_no
     *
     * @return the value of b_product_info.product_no
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_no
     *
     * @param productNo the value for b_product_info.product_no
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_money
     *
     * @return the value of b_product_info.product_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public BigDecimal getProductMoney() {
        return productMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_money
     *
     * @param productMoney the value for b_product_info.product_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setProductMoney(BigDecimal productMoney) {
        this.productMoney = productMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.left_product_money
     *
     * @return the value of b_product_info.left_product_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public BigDecimal getLeftProductMoney() {
        return leftProductMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.left_product_money
     *
     * @param leftProductMoney the value for b_product_info.left_product_money
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setLeftProductMoney(BigDecimal leftProductMoney) {
        this.leftProductMoney = leftProductMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.bid_min_limit
     *
     * @return the value of b_product_info.bid_min_limit
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public BigDecimal getBidMinLimit() {
        return bidMinLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.bid_min_limit
     *
     * @param bidMinLimit the value for b_product_info.bid_min_limit
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setBidMinLimit(BigDecimal bidMinLimit) {
        this.bidMinLimit = bidMinLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.bid_max_limit
     *
     * @return the value of b_product_info.bid_max_limit
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public BigDecimal getBidMaxLimit() {
        return bidMaxLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.bid_max_limit
     *
     * @param bidMaxLimit the value for b_product_info.bid_max_limit
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setBidMaxLimit(BigDecimal bidMaxLimit) {
        this.bidMaxLimit = bidMaxLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_status
     *
     * @return the value of b_product_info.product_status
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Integer getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_status
     *
     * @param productStatus the value for b_product_info.product_status
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setProductStatus(Integer productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_full_time
     *
     * @return the value of b_product_info.product_full_time
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public Date getProductFullTime() {
        return productFullTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_full_time
     *
     * @param productFullTime the value for b_product_info.product_full_time
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setProductFullTime(Date productFullTime) {
        this.productFullTime = productFullTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_info.product_desc
     *
     * @return the value of b_product_info.product_desc
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_info.product_desc
     *
     * @param productDesc the value for b_product_info.product_desc
     *
     * @mbg.generated Wed Jul 05 06:42:36 CST 2023
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }
}